// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: FlightProtocol_v3.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from FlightProtocol_v3.proto</summary>
public static partial class FlightProtocolV3Reflection {

  #region Descriptor
  /// <summary>File descriptor for FlightProtocol_v3.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static FlightProtocolV3Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdGbGlnaHRQcm90b2NvbF92My5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3Rp",
          "bWVzdGFtcC5wcm90byI0CgZBZ2VuY3kSDAoEbmFtZRgBIAEoCRIQCghwYXNz",
          "d29yZBgCIAEoCRIKCgJpZBgDIAEoCSJbCg5Cb29raW5nRGV0YWlscxIQCghp",
          "ZEZsaWdodBgBIAEoAxISCgpjbGllbnROYW1lGAIgASgJEhIKCnBhc3Nlbmdl",
          "cnMYAyADKAkSDwoHYWRkcmVzcxgEIAEoCSJbCg1GbGlnaHREZXRhaWxzEhMK",
          "C2Rlc3RpbmF0aW9uGAEgASgJEjUKEWRlcGFydHVyZURhdGVUaW1lGAIgASgL",
          "MhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCKJAQoGRmxpZ2h0EgoKAmlk",
          "GAEgASgDEhMKC2Rlc3RpbmF0aW9uGAIgASgJEjUKEWRlcGFydHVyZURhdGVU",
          "aW1lGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIPCgdhaXJw",
          "b3J0GAQgASgJEhYKDmF2YWlsYWJsZVNlYXRzGAUgASgFIisKBUxvZ2luEhAK",
          "CHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIpoCCg1GbGlnaHRS",
          "ZXF1ZXN0EiEKBHR5cGUYASABKA4yEy5GbGlnaHRSZXF1ZXN0LlR5cGUSFwoF",
          "bG9naW4YAiABKAsyBi5Mb2dpbkgAEhkKBmFnZW5jeRgDIAEoCzIHLkFnZW5j",
          "eUgAEicKDWZsaWdodERldGFpbHMYBCABKAsyDi5GbGlnaHREZXRhaWxzSAAS",
          "KQoOYm9va2luZ0RldGFpbHMYBSABKAsyDy5Cb29raW5nRGV0YWlsc0gAIlMK",
          "BFR5cGUSCwoHVW5rbm93bhAAEgkKBUxvZ2luEAESCgoGTG9nb3V0EAISBwoD",
          "QnV5EAMSEwoPR2V0Rm91bmRGbGlnaHRzEAQSCQoFQ2xlYXIQBUIJCgdwYXls",
          "b2FkIsABCg5GbGlnaHRSZXNwb25zZRIiCgR0eXBlGAEgASgOMhQuRmxpZ2h0",
          "UmVzcG9uc2UuVHlwZRINCgVlcnJvchgCIAEoCRIYCgdmbGlnaHRzGAMgAygL",
          "MgcuRmxpZ2h0ImEKBFR5cGUSCwoHVW5rbm93bhAAEgYKAk9rEAESCQoFRXJy",
          "b3IQAhIRCg1UaWNrZXRzQm91Z2h0EAMSEwoPR2V0Rm91bmRGbGlnaHRzEAQS",
          "EQoNR2V0QWxsRkxpZ2h0cxAFQjYKI2ZsaWdodC5uZXR3b3JraW5nLnByb3Rv",
          "YnVmZnByb3RvY29sQg9GbGlnaHRQcm90b2J1ZnNiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Agency), global::Agency.Parser, new[]{ "Name", "Password", "Id" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BookingDetails), global::BookingDetails.Parser, new[]{ "IdFlight", "ClientName", "Passengers", "Address" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FlightDetails), global::FlightDetails.Parser, new[]{ "Destination", "DepartureDateTime" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Flight), global::Flight.Parser, new[]{ "Id", "Destination", "DepartureDateTime", "Airport", "AvailableSeats" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Login), global::Login.Parser, new[]{ "Username", "Password" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FlightRequest), global::FlightRequest.Parser, new[]{ "Type", "Login", "Agency", "FlightDetails", "BookingDetails" }, new[]{ "Payload" }, new[]{ typeof(global::FlightRequest.Types.Type) }, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::FlightResponse), global::FlightResponse.Parser, new[]{ "Type", "Error", "Flights" }, null, new[]{ typeof(global::FlightResponse.Types.Type) }, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Agency : pb::IMessage<Agency>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Agency> _parser = new pb::MessageParser<Agency>(() => new Agency());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Agency> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FlightProtocolV3Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Agency() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Agency(Agency other) : this() {
    name_ = other.name_;
    password_ = other.password_;
    id_ = other.id_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Agency Clone() {
    return new Agency(this);
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 1;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 2;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 3;
  private string id_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Id {
    get { return id_; }
    set {
      id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Agency);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Agency other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Name != other.Name) return false;
    if (Password != other.Password) return false;
    if (Id != other.Id) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (Id.Length != 0) hash ^= Id.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (Id.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Id);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Name.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Name);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (Id.Length != 0) {
      output.WriteRawTag(26);
      output.WriteString(Id);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (Id.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Agency other) {
    if (other == null) {
      return;
    }
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    if (other.Id.Length != 0) {
      Id = other.Id;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
        case 26: {
          Id = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Name = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
        case 26: {
          Id = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class BookingDetails : pb::IMessage<BookingDetails>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BookingDetails> _parser = new pb::MessageParser<BookingDetails>(() => new BookingDetails());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BookingDetails> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FlightProtocolV3Reflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BookingDetails() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BookingDetails(BookingDetails other) : this() {
    idFlight_ = other.idFlight_;
    clientName_ = other.clientName_;
    passengers_ = other.passengers_.Clone();
    address_ = other.address_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BookingDetails Clone() {
    return new BookingDetails(this);
  }

  /// <summary>Field number for the "idFlight" field.</summary>
  public const int IdFlightFieldNumber = 1;
  private long idFlight_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long IdFlight {
    get { return idFlight_; }
    set {
      idFlight_ = value;
    }
  }

  /// <summary>Field number for the "clientName" field.</summary>
  public const int ClientNameFieldNumber = 2;
  private string clientName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string ClientName {
    get { return clientName_; }
    set {
      clientName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "passengers" field.</summary>
  public const int PassengersFieldNumber = 3;
  private static readonly pb::FieldCodec<string> _repeated_passengers_codec
      = pb::FieldCodec.ForString(26);
  private readonly pbc::RepeatedField<string> passengers_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> Passengers {
    get { return passengers_; }
  }

  /// <summary>Field number for the "address" field.</summary>
  public const int AddressFieldNumber = 4;
  private string address_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Address {
    get { return address_; }
    set {
      address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BookingDetails);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BookingDetails other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IdFlight != other.IdFlight) return false;
    if (ClientName != other.ClientName) return false;
    if(!passengers_.Equals(other.passengers_)) return false;
    if (Address != other.Address) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (IdFlight != 0L) hash ^= IdFlight.GetHashCode();
    if (ClientName.Length != 0) hash ^= ClientName.GetHashCode();
    hash ^= passengers_.GetHashCode();
    if (Address.Length != 0) hash ^= Address.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (IdFlight != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(IdFlight);
    }
    if (ClientName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ClientName);
    }
    passengers_.WriteTo(output, _repeated_passengers_codec);
    if (Address.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Address);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (IdFlight != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(IdFlight);
    }
    if (ClientName.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ClientName);
    }
    passengers_.WriteTo(ref output, _repeated_passengers_codec);
    if (Address.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Address);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (IdFlight != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(IdFlight);
    }
    if (ClientName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientName);
    }
    size += passengers_.CalculateSize(_repeated_passengers_codec);
    if (Address.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BookingDetails other) {
    if (other == null) {
      return;
    }
    if (other.IdFlight != 0L) {
      IdFlight = other.IdFlight;
    }
    if (other.ClientName.Length != 0) {
      ClientName = other.ClientName;
    }
    passengers_.Add(other.passengers_);
    if (other.Address.Length != 0) {
      Address = other.Address;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          IdFlight = input.ReadInt64();
          break;
        }
        case 18: {
          ClientName = input.ReadString();
          break;
        }
        case 26: {
          passengers_.AddEntriesFrom(input, _repeated_passengers_codec);
          break;
        }
        case 34: {
          Address = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          IdFlight = input.ReadInt64();
          break;
        }
        case 18: {
          ClientName = input.ReadString();
          break;
        }
        case 26: {
          passengers_.AddEntriesFrom(ref input, _repeated_passengers_codec);
          break;
        }
        case 34: {
          Address = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class FlightDetails : pb::IMessage<FlightDetails>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FlightDetails> _parser = new pb::MessageParser<FlightDetails>(() => new FlightDetails());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FlightDetails> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FlightProtocolV3Reflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightDetails() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightDetails(FlightDetails other) : this() {
    destination_ = other.destination_;
    departureDateTime_ = other.departureDateTime_ != null ? other.departureDateTime_.Clone() : null;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightDetails Clone() {
    return new FlightDetails(this);
  }

  /// <summary>Field number for the "destination" field.</summary>
  public const int DestinationFieldNumber = 1;
  private string destination_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Destination {
    get { return destination_; }
    set {
      destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "departureDateTime" field.</summary>
  public const int DepartureDateTimeFieldNumber = 2;
  private global::Google.Protobuf.WellKnownTypes.Timestamp departureDateTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp DepartureDateTime {
    get { return departureDateTime_; }
    set {
      departureDateTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FlightDetails);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FlightDetails other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Destination != other.Destination) return false;
    if (!object.Equals(DepartureDateTime, other.DepartureDateTime)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Destination.Length != 0) hash ^= Destination.GetHashCode();
    if (departureDateTime_ != null) hash ^= DepartureDateTime.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Destination.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Destination);
    }
    if (departureDateTime_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(DepartureDateTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Destination.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Destination);
    }
    if (departureDateTime_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(DepartureDateTime);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Destination.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
    }
    if (departureDateTime_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DepartureDateTime);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FlightDetails other) {
    if (other == null) {
      return;
    }
    if (other.Destination.Length != 0) {
      Destination = other.Destination;
    }
    if (other.departureDateTime_ != null) {
      if (departureDateTime_ == null) {
        DepartureDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      DepartureDateTime.MergeFrom(other.DepartureDateTime);
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Destination = input.ReadString();
          break;
        }
        case 18: {
          if (departureDateTime_ == null) {
            DepartureDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(DepartureDateTime);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Destination = input.ReadString();
          break;
        }
        case 18: {
          if (departureDateTime_ == null) {
            DepartureDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(DepartureDateTime);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Flight : pb::IMessage<Flight>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Flight> _parser = new pb::MessageParser<Flight>(() => new Flight());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Flight> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FlightProtocolV3Reflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Flight() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Flight(Flight other) : this() {
    id_ = other.id_;
    destination_ = other.destination_;
    departureDateTime_ = other.departureDateTime_ != null ? other.departureDateTime_.Clone() : null;
    airport_ = other.airport_;
    availableSeats_ = other.availableSeats_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Flight Clone() {
    return new Flight(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private long id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "destination" field.</summary>
  public const int DestinationFieldNumber = 2;
  private string destination_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Destination {
    get { return destination_; }
    set {
      destination_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "departureDateTime" field.</summary>
  public const int DepartureDateTimeFieldNumber = 3;
  private global::Google.Protobuf.WellKnownTypes.Timestamp departureDateTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Google.Protobuf.WellKnownTypes.Timestamp DepartureDateTime {
    get { return departureDateTime_; }
    set {
      departureDateTime_ = value;
    }
  }

  /// <summary>Field number for the "airport" field.</summary>
  public const int AirportFieldNumber = 4;
  private string airport_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Airport {
    get { return airport_; }
    set {
      airport_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "availableSeats" field.</summary>
  public const int AvailableSeatsFieldNumber = 5;
  private int availableSeats_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int AvailableSeats {
    get { return availableSeats_; }
    set {
      availableSeats_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Flight);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Flight other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Destination != other.Destination) return false;
    if (!object.Equals(DepartureDateTime, other.DepartureDateTime)) return false;
    if (Airport != other.Airport) return false;
    if (AvailableSeats != other.AvailableSeats) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0L) hash ^= Id.GetHashCode();
    if (Destination.Length != 0) hash ^= Destination.GetHashCode();
    if (departureDateTime_ != null) hash ^= DepartureDateTime.GetHashCode();
    if (Airport.Length != 0) hash ^= Airport.GetHashCode();
    if (AvailableSeats != 0) hash ^= AvailableSeats.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Destination.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Destination);
    }
    if (departureDateTime_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(DepartureDateTime);
    }
    if (Airport.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Airport);
    }
    if (AvailableSeats != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(AvailableSeats);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(Id);
    }
    if (Destination.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Destination);
    }
    if (departureDateTime_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(DepartureDateTime);
    }
    if (Airport.Length != 0) {
      output.WriteRawTag(34);
      output.WriteString(Airport);
    }
    if (AvailableSeats != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(AvailableSeats);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
    }
    if (Destination.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Destination);
    }
    if (departureDateTime_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(DepartureDateTime);
    }
    if (Airport.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Airport);
    }
    if (AvailableSeats != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(AvailableSeats);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Flight other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0L) {
      Id = other.Id;
    }
    if (other.Destination.Length != 0) {
      Destination = other.Destination;
    }
    if (other.departureDateTime_ != null) {
      if (departureDateTime_ == null) {
        DepartureDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
      }
      DepartureDateTime.MergeFrom(other.DepartureDateTime);
    }
    if (other.Airport.Length != 0) {
      Airport = other.Airport;
    }
    if (other.AvailableSeats != 0) {
      AvailableSeats = other.AvailableSeats;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Destination = input.ReadString();
          break;
        }
        case 26: {
          if (departureDateTime_ == null) {
            DepartureDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(DepartureDateTime);
          break;
        }
        case 34: {
          Airport = input.ReadString();
          break;
        }
        case 40: {
          AvailableSeats = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt64();
          break;
        }
        case 18: {
          Destination = input.ReadString();
          break;
        }
        case 26: {
          if (departureDateTime_ == null) {
            DepartureDateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
          }
          input.ReadMessage(DepartureDateTime);
          break;
        }
        case 34: {
          Airport = input.ReadString();
          break;
        }
        case 40: {
          AvailableSeats = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class Login : pb::IMessage<Login>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Login> _parser = new pb::MessageParser<Login>(() => new Login());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Login> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FlightProtocolV3Reflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Login() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Login(Login other) : this() {
    username_ = other.username_;
    password_ = other.password_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Login Clone() {
    return new Login(this);
  }

  /// <summary>Field number for the "username" field.</summary>
  public const int UsernameFieldNumber = 1;
  private string username_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Username {
    get { return username_; }
    set {
      username_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "password" field.</summary>
  public const int PasswordFieldNumber = 2;
  private string password_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Password {
    get { return password_; }
    set {
      password_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Login);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Login other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Username != other.Username) return false;
    if (Password != other.Password) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Username.Length != 0) hash ^= Username.GetHashCode();
    if (Password.Length != 0) hash ^= Password.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Username.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Username.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Username);
    }
    if (Password.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Password);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Username.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Username);
    }
    if (Password.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Password);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Login other) {
    if (other == null) {
      return;
    }
    if (other.Username.Length != 0) {
      Username = other.Username;
    }
    if (other.Password.Length != 0) {
      Password = other.Password;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Username = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Username = input.ReadString();
          break;
        }
        case 18: {
          Password = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class FlightRequest : pb::IMessage<FlightRequest>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FlightRequest> _parser = new pb::MessageParser<FlightRequest>(() => new FlightRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FlightRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FlightProtocolV3Reflection.Descriptor.MessageTypes[5]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightRequest(FlightRequest other) : this() {
    type_ = other.type_;
    switch (other.PayloadCase) {
      case PayloadOneofCase.Login:
        Login = other.Login.Clone();
        break;
      case PayloadOneofCase.Agency:
        Agency = other.Agency.Clone();
        break;
      case PayloadOneofCase.FlightDetails:
        FlightDetails = other.FlightDetails.Clone();
        break;
      case PayloadOneofCase.BookingDetails:
        BookingDetails = other.BookingDetails.Clone();
        break;
    }

    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightRequest Clone() {
    return new FlightRequest(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::FlightRequest.Types.Type type_ = global::FlightRequest.Types.Type.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::FlightRequest.Types.Type Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "login" field.</summary>
  public const int LoginFieldNumber = 2;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Login Login {
    get { return payloadCase_ == PayloadOneofCase.Login ? (global::Login) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Login;
    }
  }

  /// <summary>Field number for the "agency" field.</summary>
  public const int AgencyFieldNumber = 3;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Agency Agency {
    get { return payloadCase_ == PayloadOneofCase.Agency ? (global::Agency) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Agency;
    }
  }

  /// <summary>Field number for the "flightDetails" field.</summary>
  public const int FlightDetailsFieldNumber = 4;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::FlightDetails FlightDetails {
    get { return payloadCase_ == PayloadOneofCase.FlightDetails ? (global::FlightDetails) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.FlightDetails;
    }
  }

  /// <summary>Field number for the "bookingDetails" field.</summary>
  public const int BookingDetailsFieldNumber = 5;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::BookingDetails BookingDetails {
    get { return payloadCase_ == PayloadOneofCase.BookingDetails ? (global::BookingDetails) payload_ : null; }
    set {
      payload_ = value;
      payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.BookingDetails;
    }
  }

  private object payload_;
  /// <summary>Enum of possible cases for the "payload" oneof.</summary>
  public enum PayloadOneofCase {
    None = 0,
    Login = 2,
    Agency = 3,
    FlightDetails = 4,
    BookingDetails = 5,
  }
  private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PayloadOneofCase PayloadCase {
    get { return payloadCase_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearPayload() {
    payloadCase_ = PayloadOneofCase.None;
    payload_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FlightRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FlightRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (!object.Equals(Login, other.Login)) return false;
    if (!object.Equals(Agency, other.Agency)) return false;
    if (!object.Equals(FlightDetails, other.FlightDetails)) return false;
    if (!object.Equals(BookingDetails, other.BookingDetails)) return false;
    if (PayloadCase != other.PayloadCase) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::FlightRequest.Types.Type.Unknown) hash ^= Type.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Login) hash ^= Login.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.Agency) hash ^= Agency.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.FlightDetails) hash ^= FlightDetails.GetHashCode();
    if (payloadCase_ == PayloadOneofCase.BookingDetails) hash ^= BookingDetails.GetHashCode();
    hash ^= (int) payloadCase_;
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::FlightRequest.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (payloadCase_ == PayloadOneofCase.Login) {
      output.WriteRawTag(18);
      output.WriteMessage(Login);
    }
    if (payloadCase_ == PayloadOneofCase.Agency) {
      output.WriteRawTag(26);
      output.WriteMessage(Agency);
    }
    if (payloadCase_ == PayloadOneofCase.FlightDetails) {
      output.WriteRawTag(34);
      output.WriteMessage(FlightDetails);
    }
    if (payloadCase_ == PayloadOneofCase.BookingDetails) {
      output.WriteRawTag(42);
      output.WriteMessage(BookingDetails);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::FlightRequest.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (payloadCase_ == PayloadOneofCase.Login) {
      output.WriteRawTag(18);
      output.WriteMessage(Login);
    }
    if (payloadCase_ == PayloadOneofCase.Agency) {
      output.WriteRawTag(26);
      output.WriteMessage(Agency);
    }
    if (payloadCase_ == PayloadOneofCase.FlightDetails) {
      output.WriteRawTag(34);
      output.WriteMessage(FlightDetails);
    }
    if (payloadCase_ == PayloadOneofCase.BookingDetails) {
      output.WriteRawTag(42);
      output.WriteMessage(BookingDetails);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::FlightRequest.Types.Type.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (payloadCase_ == PayloadOneofCase.Login) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Login);
    }
    if (payloadCase_ == PayloadOneofCase.Agency) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Agency);
    }
    if (payloadCase_ == PayloadOneofCase.FlightDetails) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FlightDetails);
    }
    if (payloadCase_ == PayloadOneofCase.BookingDetails) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(BookingDetails);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FlightRequest other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::FlightRequest.Types.Type.Unknown) {
      Type = other.Type;
    }
    switch (other.PayloadCase) {
      case PayloadOneofCase.Login:
        if (Login == null) {
          Login = new global::Login();
        }
        Login.MergeFrom(other.Login);
        break;
      case PayloadOneofCase.Agency:
        if (Agency == null) {
          Agency = new global::Agency();
        }
        Agency.MergeFrom(other.Agency);
        break;
      case PayloadOneofCase.FlightDetails:
        if (FlightDetails == null) {
          FlightDetails = new global::FlightDetails();
        }
        FlightDetails.MergeFrom(other.FlightDetails);
        break;
      case PayloadOneofCase.BookingDetails:
        if (BookingDetails == null) {
          BookingDetails = new global::BookingDetails();
        }
        BookingDetails.MergeFrom(other.BookingDetails);
        break;
    }

    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::FlightRequest.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          global::Login subBuilder = new global::Login();
          if (payloadCase_ == PayloadOneofCase.Login) {
            subBuilder.MergeFrom(Login);
          }
          input.ReadMessage(subBuilder);
          Login = subBuilder;
          break;
        }
        case 26: {
          global::Agency subBuilder = new global::Agency();
          if (payloadCase_ == PayloadOneofCase.Agency) {
            subBuilder.MergeFrom(Agency);
          }
          input.ReadMessage(subBuilder);
          Agency = subBuilder;
          break;
        }
        case 34: {
          global::FlightDetails subBuilder = new global::FlightDetails();
          if (payloadCase_ == PayloadOneofCase.FlightDetails) {
            subBuilder.MergeFrom(FlightDetails);
          }
          input.ReadMessage(subBuilder);
          FlightDetails = subBuilder;
          break;
        }
        case 42: {
          global::BookingDetails subBuilder = new global::BookingDetails();
          if (payloadCase_ == PayloadOneofCase.BookingDetails) {
            subBuilder.MergeFrom(BookingDetails);
          }
          input.ReadMessage(subBuilder);
          BookingDetails = subBuilder;
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::FlightRequest.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          global::Login subBuilder = new global::Login();
          if (payloadCase_ == PayloadOneofCase.Login) {
            subBuilder.MergeFrom(Login);
          }
          input.ReadMessage(subBuilder);
          Login = subBuilder;
          break;
        }
        case 26: {
          global::Agency subBuilder = new global::Agency();
          if (payloadCase_ == PayloadOneofCase.Agency) {
            subBuilder.MergeFrom(Agency);
          }
          input.ReadMessage(subBuilder);
          Agency = subBuilder;
          break;
        }
        case 34: {
          global::FlightDetails subBuilder = new global::FlightDetails();
          if (payloadCase_ == PayloadOneofCase.FlightDetails) {
            subBuilder.MergeFrom(FlightDetails);
          }
          input.ReadMessage(subBuilder);
          FlightDetails = subBuilder;
          break;
        }
        case 42: {
          global::BookingDetails subBuilder = new global::BookingDetails();
          if (payloadCase_ == PayloadOneofCase.BookingDetails) {
            subBuilder.MergeFrom(BookingDetails);
          }
          input.ReadMessage(subBuilder);
          BookingDetails = subBuilder;
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the FlightRequest message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("Unknown")] Unknown = 0,
      [pbr::OriginalName("Login")] Login = 1,
      [pbr::OriginalName("Logout")] Logout = 2,
      [pbr::OriginalName("Buy")] Buy = 3,
      [pbr::OriginalName("GetFoundFlights")] GetFoundFlights = 4,
      [pbr::OriginalName("Clear")] Clear = 5,
    }

  }
  #endregion

}

public sealed partial class FlightResponse : pb::IMessage<FlightResponse>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<FlightResponse> _parser = new pb::MessageParser<FlightResponse>(() => new FlightResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<FlightResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::FlightProtocolV3Reflection.Descriptor.MessageTypes[6]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightResponse(FlightResponse other) : this() {
    type_ = other.type_;
    error_ = other.error_;
    flights_ = other.flights_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public FlightResponse Clone() {
    return new FlightResponse(this);
  }

  /// <summary>Field number for the "type" field.</summary>
  public const int TypeFieldNumber = 1;
  private global::FlightResponse.Types.Type type_ = global::FlightResponse.Types.Type.Unknown;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::FlightResponse.Types.Type Type {
    get { return type_; }
    set {
      type_ = value;
    }
  }

  /// <summary>Field number for the "error" field.</summary>
  public const int ErrorFieldNumber = 2;
  private string error_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Error {
    get { return error_; }
    set {
      error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "flights" field.</summary>
  public const int FlightsFieldNumber = 3;
  private static readonly pb::FieldCodec<global::Flight> _repeated_flights_codec
      = pb::FieldCodec.ForMessage(26, global::Flight.Parser);
  private readonly pbc::RepeatedField<global::Flight> flights_ = new pbc::RepeatedField<global::Flight>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::Flight> Flights {
    get { return flights_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as FlightResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(FlightResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Type != other.Type) return false;
    if (Error != other.Error) return false;
    if(!flights_.Equals(other.flights_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Type != global::FlightResponse.Types.Type.Unknown) hash ^= Type.GetHashCode();
    if (Error.Length != 0) hash ^= Error.GetHashCode();
    hash ^= flights_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Type != global::FlightResponse.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Error);
    }
    flights_.WriteTo(output, _repeated_flights_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Type != global::FlightResponse.Types.Type.Unknown) {
      output.WriteRawTag(8);
      output.WriteEnum((int) Type);
    }
    if (Error.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Error);
    }
    flights_.WriteTo(ref output, _repeated_flights_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Type != global::FlightResponse.Types.Type.Unknown) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
    }
    if (Error.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
    }
    size += flights_.CalculateSize(_repeated_flights_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(FlightResponse other) {
    if (other == null) {
      return;
    }
    if (other.Type != global::FlightResponse.Types.Type.Unknown) {
      Type = other.Type;
    }
    if (other.Error.Length != 0) {
      Error = other.Error;
    }
    flights_.Add(other.flights_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Type = (global::FlightResponse.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          Error = input.ReadString();
          break;
        }
        case 26: {
          flights_.AddEntriesFrom(input, _repeated_flights_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Type = (global::FlightResponse.Types.Type) input.ReadEnum();
          break;
        }
        case 18: {
          Error = input.ReadString();
          break;
        }
        case 26: {
          flights_.AddEntriesFrom(ref input, _repeated_flights_codec);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the FlightResponse message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum Type {
      [pbr::OriginalName("Unknown")] Unknown = 0,
      [pbr::OriginalName("Ok")] Ok = 1,
      [pbr::OriginalName("Error")] Error = 2,
      [pbr::OriginalName("TicketsBought")] TicketsBought = 3,
      [pbr::OriginalName("GetFoundFlights")] GetFoundFlights = 4,
      [pbr::OriginalName("GetAllFLights")] GetAllFlights = 5,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
